import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import { AuthProvider } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-full bg-fixed bg-gradient-to-b from-teal-500 w-100 ">
        
        <div className="main scroll-smooth">
          <AuthProvider>
          <Header />

          {children}
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
